# Generated by Django 3.2.13 on 2022-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[(0, 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Ads', 'Ads'), ('others', 'Others')], default=0, max_length=100)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
