# Generated by Django 3.2.13 on 2022-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220428_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='open_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
