# Generated by Django 3.2.13 on 2022-05-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
