# Generated by Django 3.2.13 on 2022-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_testimony_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
