# Generated by Django 3.2.13 on 2022-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[(0, 'Select Gender'), ('male', 'Male'), ('female', 'Female')], default=0, max_length=50),
        ),
    ]
