# Generated by Django 3.2.13 on 2022-05-16 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyevent',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 14, 16, 57, 287793)),
        ),
        migrations.AddField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(14, 16, 57, 285794)),
        ),
    ]
