# Generated by Django 3.2.13 on 2022-05-16 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220516_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 15, 25, 12, 287836)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='day',
            field=models.CharField(choices=[(0, 'Select Day of Week'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 25, 12, 287836)),
        ),
    ]
