# Generated by Django 3.2.13 on 2022-05-31 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220520_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weeklyevent',
            name='name',
        ),
        migrations.AddField(
            model_name='actualevent',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 12, 7, 16, 756352)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 7, 16, 755351)),
        ),
    ]
