# Generated by Django 3.2.13 on 2022-06-01 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220601_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 11, 48, 17, 716003)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 48, 17, 715006)),
        ),
    ]
