# Generated by Django 3.2.13 on 2022-06-03 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220601_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 10, 54, 18, 236918)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 54, 18, 236918)),
        ),
    ]
