# Generated by Django 3.2.13 on 2022-06-03 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20220603_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 11, 14, 44, 247199)),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 14, 44, 246220)),
        ),
    ]
