# Generated by Django 3.2.13 on 2022-06-04 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20220603_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualevent',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 12, 36, 7, 368774)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 36, 7, 368774)),
        ),
    ]
