# Generated by Django 3.2.13 on 2022-06-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20220604_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacher',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 8, 45, 47, 466963)),
        ),
        migrations.AlterField(
            model_name='weeklyevent',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 45, 47, 465963)),
        ),
    ]
