# Generated by Django 3.2.13 on 2022-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20220605_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/preacher'),
        ),
    ]
